### ISSUE TITLE
TODO list for Documentation

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#101]
Todo:
- [ ] Team member accreditation ~~(Python script through Travis that populates team list page automatically on commits to `master`)~~
  - ~~`git shortlog -s -n --no-merges`~~
  - ~~Custom additions (outside contributors, eg. models)~~
- [x] Functions list generator (Python script through Travis) (#991)
  - [x] Change links from `acre.idi-systems.com` to new pages
- [x] Class names list ~~generator (Python script through Travis)~~
- ~~Change colours to dark yellow (like ACRE2 logo) - https://github.com/IDI-Systems/acre2/tree/docsYellowTheme~~ it looks fugly

**Comment by jonpas** [comment]
> Team member accreditation

I don't think I'll ever get around to this, and honestly, I think it's fine if we just link this somewhere in the documentation: https://github.com/IDI-Systems/acre2/graphs/contributors

**Comment by jonpas** [comment]
Public class names were documented in e136d31f13f6e49000aad978d5632e3bffdc5e90. It really isn't worth doing a script for this, looking at it there are very few public classes anyways.
