### ISSUE TITLE
Vehicle rack issues

### ISSUE THREAD

**Issue by TheMagnetar** [IDI-Systems/acre2#325]
Investigate the following:

- [ ] Framedrop when setting the rack as active (might be fixed in #332).
- [x] Garbage-collecting message appears when deleting the vehicle (might be fixed in #324).
- [ ] When using the rack, the radio start transmitting/end transmitting sound appeared doubled (might be fixed in #332).
- [x] Add missing racks to vanilla vehicles.

**Comment by TheMagnetar** [comment]
This was partially solved.
