### ISSUE TITLE
TODO list for Intercom rework and Racks

### ISSUE THREAD

**Issue by jonpas** [IDI-Systems/acre2#483]
- UI
  - [x] Movable element in layout editor
  - [x] Prevent hiding when opening displays
  - [x] Support for variable amount of intercoms and racks (auto-resize in height)
- ACE3 Actions
  - [x] Streamline action names (length, capitalization)
  - [x] Group "Transmit Only", "Receive Only" and "Transmit and Receive" under an action point (like spatial "Ear" group)
  - [x] Fix "Unmountable (Locked)" never showing up.
- ACE3 Hints
  - ~~Streamline hint texts (length, capitalization)~~
- Keys
  - [x] Streamline key names (capitalization)
  - [x] Streamline default binds with older keys
    - Unbind both of them by default (voice activation is default and there are ACE3 interactions)
  - ~~Make "Intercom PTT" actually work like PTT (and not activate toggle)~~
- Fixes
  - [x] Fix infantry phone warning (config).
  - [x] Add master station to copilots (config)
  - [x] `[ACRE] (sys_data) WARNING: System event handler function attachComponent is not defined! idi\acre\addons\sys_data\fnc_noApiSystemFunction.sqf:21`

**Comment by TheMagnetar** [comment]
Updated description with fixes so that we can track them more easily.

**Comment by jonpas** [comment]
All done.
